### ISSUE TITLE
Blender crashes when assigning mod directory on a mesh that already exists

### ISSUE THREAD

**Issue by UnLuCkYcHaRrnS** [enenra/space-engineers-utilities#343] opened 2022-09-25 08:05 UTC
[BlamiteIngot.zip](https://github.com/enenra/space-engineers-utilities/files/9640270/BlamiteIngot.zip)
Apparently it doesn't happen to some people, but it's pretty consistent for me. The attached file is affected for me. I haven't noticed any significant factors beyond that there is already a mesh in the scene. I can set the mod path and the export path defaults to Models/CubeBlocks/, when I try to change it to Models/Weapons it crashes.
The mod I am currently working on doesn't have a CubeBlocks section so I think SEUT is just taking a dump because the initialized value is invalid

**Comment by enenra** [comment] 2022-10-22 13:01
Hi
Sorry but I cannot reproduce this, even with your file. Neither do I get "Cubeblocks" in the path nor does Blender crash when I change the path. 

Incidentally, there is no code that can set it to CubeBlocks so I'm not sure how that is happening in the first place. Could you try putting the blend file into a different folder and trying different locations for the mod folder to check if it always happens?

**Comment by enenra** [comment] 2022-12-10 10:35
With no further activity on this issue for quite a while, I'm going to close it. 

Please let me know if there are any further developments.

**Closed by enenra** 2022-12-10 10:35 UTC
Labels: bug, export, can't reproduce
