### ISSUE TITLE
Opening .blend file that has been saved in edit mode gives error.

### ISSUE THREAD

**Issue by cstahlhut** [enenra/space-engineers-utilities#184] opened 2020-03-17 00:32 UTC
```py
Traceback (most recent call last):
  File "C:\Users\Cheyne\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\src\seut_pt_toolbar.py", line 22, in draw
    addon_updater_ops.check_for_update_background()
  File "C:\Users\Cheyne\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\src\addon_updater_ops.py", line 741, in check_for_update_background
    updater.check_for_update_async(background_update_callback)
  File "C:\Users\Cheyne\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\src\addon_updater.py", line 1056, in check_for_update_async
    callback(True)
  File "C:\Users\Cheyne\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\src\addon_updater_ops.py", line 663, in background_update_callback
    bpy.app.handlers.scene_update_post and \
AttributeError: 'bpy.app.handlers' object has no attribute 'scene_update_post'
```

**Comment by enenra** [comment] 2020-03-23 11:24
Well, unfortunately this is the addon updater and thus a nightmare to debug. Not sure I can do anything about this tbh. Also, are you 100% this is directly caused by saving in edit mode? There's a bunch of errors with the addon updater than happen in relation to it being launched from VSC etc. that I think this might be related to.

**Comment by enenra** [comment] 2020-08-18 20:36
Since the addon updater has been removed, this should be fixed.

**Closed by enenra** 2020-08-18 20:36 UTC
Labels: bug
